ques = [
    # "Which department does Ujjawal Roy works in?",
    # "Brief me about MI-516",
    # "How many Python devs do we have?",
    # "Has Nency Patel filled her logs?",
    # "Who is the CEO of MindInventory?",
    # "Which python devs have not filled their logs today?",
    # "I need 3 devs who are proficient in python and sql"
    # "Who all are in probation?",
    "Who is on leave today? ",
    "Who is on leave this week? ",
    "Who is on WFH today? ",
    "Who is on WFH this week? ",
    "How many people are free for from each department? ",
    "How many people came late today? ",
    "Who did not fill the logs yesterday? ",
    "Which projects have less than 20 bucket hours today? ",
    "Which projects do we need to send invoice to in hire today? ",
    "Give me a list of upcoming milestones for Fixed cost projects ",
    "Did we send invoice for (Project Name) ? If yes when ",
    "How many interviews do i have take today and what time? ",
    "Who is allocated in which project? and for how many hours? ",
    "Whats for lunch today? ",
    "Whats for lunch tomorrow? ",
    "How many leaves do i have? ",
    "Which tasks are assgined to me? ",
    "Who has the (Device name)? ",
    "Whose birthday is it today? ",
    "Whose birthday was yesterday? ",
    "Whose birthday was last week? ",
    "Whose birthday is next week? ",
    "Whose birthday is tomorrow? ",
    "Whose Anniversary is it today? ",
    "Whose Anniversary was yesterday? ",
    "Whose Anniversary was last week? ",
    "Whose Anniversary is next week? ",
    "Whose Anniversary is tomorrow? ",
    "Show me my team attendance - For today ",
    "Did i check for lunch today? ",
    "Apply for leave ",
    "Apply for Wfh ",
    "Add a project ",
    "Add a CR"
]
